### ISSUE TITLE
Required dependency gen_stage fails compilation

### ISSUE THREAD

**Issue by tpinckard** [royveshovda/xgps#4]
Encountered issue on raspberry pi (Raspbian GNU/Linux 9 (stretch)). 

running `iex -S mix` results in the following error stack:
```
ex -S mix
Erlang/OTP 20 [erts-9.3] [source] [smp:4:4] [ds:4:4:10] [async-threads:10] [kernel-poll:false]

==> gen_stage
Compiling 17 files (.ex)
warning: function slice/1 required by protocol Enumerable is not implemented (in module Enumerable.Experimental.Flow)
  lib/flow.ex:1267

warning: invalid type annotation. When using the | operator to represent the union of types, make sure to wrap type annotations in parentheses: {term, term} | state :: term
  lib/gen_stage.ex:917


== Compilation error in file lib/gen_stage.ex ==
** (CompileError) lib/gen_stage.ex:917: type state/0 undefined
    (elixir) lib/kernel/typespec.ex:815: Kernel.Typespec.compile_error/2
    (elixir) lib/kernel/typespec.ex:759: Kernel.Typespec.typespec/4
    (elixir) lib/enum.ex:1430: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1430: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/kernel/typespec.ex:399: Kernel.Typespec.typespec/4
    (elixir) lib/kernel/typespec.ex:613: Kernel.Typespec.typespec/4
    (elixir) lib/kernel/typespec.ex:582: Kernel.Typespec.typespec/4
    (elixir) lib/enum.ex:1430: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
could not compile dependency :gen_stage, "mix compile" failed. You can recompile this dependency with "mix deps.compile gen_stage", update it with "mix deps.update gen_stage" or clean it with "mix deps.clean gen_stage"
```

Have run mix `deps.compile gen_stage`, `mix deps.update gen_stage`, and `mix deps.clean gen_stage` without effect. 

Attempting to bump to a newer version of gen_stage also does not resolve the issue.

Any help appreciated!

**Comment by royveshovda** [comment]
I am very sorry that I did not see this. I have been off Github for years, and completly forgotten about this project. I will try to bring it up to current versions for deps. Since this is very old, I will close now. Please reopen if needed
